### ISSUE TITLE
Add loading screen

### ISSUE THREAD

**Issue by soapsrc** [soapsrc/Project-Me-Button#14]
When you first load index.html, graphics will flash because they're still loading. Could possibly add loading screen when canvas first initiates so user doesn't have to see the flashing of graphics?

**Comment by mightymosdan** [comment]
Suggestion:
Start the page with an intro screen. This can be something like curtains opening/clouds parting etc etc. This introduces the main page via any click

**Comment by missmarlos** [comment]
Video game style help menu/intro screen that fades to real screen after x seconds so as not to interfere with primary button objective
Sample Idea:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/36892531/134801044-472ecd4b-b901-4a62-99e7-78ff65e4b59b.png">

**Comment by soapsrc** [comment]
Great idea! The fonts are really nice 😊
